### ISSUE TITLE
error using example in AutoLearn

### ISSUE THREAD

**Issue by theiman112860** [XanderHorn/autoML#4]
Hi Xander, 

Very cool project!! I ran the following example using autoLearn:

mod <- autoLearn(train = iris, target = "Species")

 and get the following errors:

 Error in stopWithJobErrorMessages(inds, vcapply(result.list[inds], as.character)) : 
  Errors occurred in 1 slave jobs, displaying at most 10 of them:

00001: Error in lognet(x, is.sparse, ix, jx, y, weights, offset, alpha, nobs,  : 
  one multinomial or binomial class has 1 or 0 observations; not allowed 

Any ideas on what to do? Thank you!

**Comment by XanderHorn** [comment]
I see the problem comes in that the iris data set is too small for the lasso, ridge and mixture model to find the optimal lambda value using cross validation and thus there are not enough outcomes in the folds. 

I would suggest to replicate the iris dataset a few times and append, then run the example again with possible succession. 

Please also keep a close eye on the following repo as it will replace autoML and autoEDA and resolve some of the model fitting issues: https://github.com/XanderHorn/lazy

Please let me know if I can close this issue?

**Comment by theiman112860** [comment]
Hi Xander,
Thank you!!  Really awesome project!!
Sincerely,
tom

-----Original Message-----

**Comment by theiman112860** [comment]
Hi Xander,
Is your Lazy package still available? I did not see it on GitHub..
Sincerely,
tom

-----Original Message-----
